apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-resources-reader
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-all-resources
roleRef:
  kind: ClusterRole
  name: all-resources-reader
  apiGroup: "rbac.authorization.k8s.io"
subjects:
  - kind: ServiceAccount
    name: icinga-kubernetes
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: icinga-kubernetes
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: icinga-kubernetes-config
  namespace: "{{ .Release.Namespace }}"
data:
  config.yml: |-
    # This is the configuration file for Icinga for Kubernetes.

    # Connection configuration for the database to which Icinga for Kubernetes synchronizes data.
    # This is also the database used in Icinga for Kubernetes Web to view and work with the data.
    database:
      # Database type. Only 'mysql' is supported yet which is the default.
      type: mysql

      # Database host or absolute Unix socket path.
      host: {{ .Values.icinga2.mysql.host | quote }}

      # Database port. By default, the MySQL port.
      port: 3306

      # Database name.
      database: {{ .Values.icinga2.mysql.ic2UserPrefix }}kubernetes

      # Database user.
      user: {{ .Values.icinga2.mysql.ic2UserPrefix }}kubernetes

      # Database password.
      password: {{ .Values.icinga2.mysql.ic2UserPass | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icinga-kubernetes
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      {{- include "icinga2.selectorLabels" . | nindent 6 }}
      component: icinga2-kubernetes

  template:
    metadata:
      labels:
        {{- include "icinga2.selectorLabels" . | nindent 8 }}
        component: icinga2-kubernetes

    spec:
      serviceAccountName: icinga-kubernetes
      # this prevents env variables for services in this namespace from being generated, as those might conflict
      enableServiceLinks: false
      containers:
        - name: icinga-kubernetes
          image: icinga/icinga-kubernetes:edge
          volumeMounts:
            - name: config-volume
              mountPath: /config.yml
              subPath: config.yml
      volumes:
        - name: config-volume
          configMap:
            name: icinga-kubernetes-config
