{{ if .Values.icinga2.influxdb.enable }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "icinga2.fullname" . }}-influxdb
  labels:
    app.kubernetes.io/component: pvc
  {{- include "icinga2.labels" . | nindent 4}}
    component: influxdb

spec:
  storageClassName: {{ .Values.icinga2.influxdb.pvc.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.icinga2.influxdb.pvc.size }}

{{ end }}
