{{ if .Values.icinga2.influxdb.enable }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icinga2.fullname" . }}-influxdb
  labels:
    {{- include "icinga2.labels" . | nindent 4 }}
    component: influxdb

spec:

  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      {{- include "icinga2.selectorLabels" . | nindent 6 }}
      component: influxdb

  template:

    metadata:
      labels:
        {{- include "icinga2.selectorLabels" . | nindent 8 }}
        component: influxdb

    spec:
      # this prevents env variables for services in this namespace from being generated, as those might conflict
      enableServiceLinks: false

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: influxdb
          image: {{ .Values.icinga2.influxdb.repository }}:{{ .Values.icinga2.influxdb.tag }}
          # command: ["sleep", "1000000"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8086

          envFrom:
          - secretRef:
              name: {{ include "icinga2.fullname" . }}-influxdb

          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb
              subPath: data

          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              memory: "2000Mi"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "icinga2.fullname" . }}-influxdb

{{ end }}
