{{ if and (eq .Values.icinga2.influxdb.enable true) (eq .Values.icinga2.influxdb.version "v1") }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icinga2.fullname" . }}-influxdb
  labels:
    {{ include "icinga2.labels" . | indent 4 | trim }}
    component: influxdb

# data:

stringData:
  INFLUXDB_HTTP_AUTH_ENABLED: "true"
  INFLUXDB_ADMIN_USER :       {{ .Values.icinga2.influxdb.adminUser | quote }}
  INFLUXDB_ADMIN_PASSWORD:    {{ .Values.icinga2.influxdb.adminPass | quote }}
  INFLUXDB_DB:                {{ .Values.icinga2.influxdb.db        | quote }}
  INFLUXDB_USER:              {{ .Values.icinga2.influxdb.user      | quote }}
  INFLUXDB_USER_PASSWORD:     {{ .Values.icinga2.influxdb.pass      | quote }}
{{ end }}

{{ if and (eq .Values.icinga2.influxdb.enable true) (eq .Values.icinga2.influxdb.version "v2") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icinga2.fullname" . }}-influxdb
  labels:
    {{ include "icinga2.labels" . | indent 4 | trim }}
    component: influxdb

# data:

stringData:
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_ORG:     {{ .Values.icinga2.influxdb.organization | quote }}
  DOCKER_INFLUXDB_INIT_BUCKET:  {{ .Values.icinga2.influxdb.bucket | quote }}
  DOCKER_INFLUXDB_INIT_USERNAME: {{ .Values.icinga2.influxdb.user      | quote }}
  DOCKER_INFLUXDB_INIT_PASSWORD: {{ .Values.icinga2.influxdb.pass      | quote }}
  DOCKER_INFLUXDB_INIT_RETENTION: {{ .Values.icinga2.influxdb.retention      | quote }}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ .Values.icinga2.influxdb.adminToken      | quote }}
{{ end }}
