---
{{ if not .Values.icinga2.master2.disable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "icinga2.fullname" . }}-master-2
  labels:
  {{- include "icinga2.labels" . | nindent 4}}
    component: icinga2-master-2

spec:

  selector:
    {{ include "icinga2.selectorLabels" . | nindent 4 }}
    component: icinga2-master-2

  ports:
    - name: icinga2
      port: 5665
      targetPort: 5665
    {{ if .Values.icinga2.IcingaDB -}}
    - name: redis
      port: 6380
      targetPort: 6380
    {{- end }}
    - name: certsvc
      port: 8080
      targetPort: 8080
{{ end }}
