---
{{ if not .Values.icinga2.master2.disable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-master-2
  labels:
    {{ include "icinga2.labels" . | indent 4 | trim }}
    component: icinga2-master-2
    app.kubernetes.io/component: pvc

spec:
  storageClassName: {{ .Values.icinga2.master2.pvc.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.icinga2.master2.pvc.size }}
{{ end }}
