{{ if .Values.nodeLocalDnsIp -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icinga2.fullname" . }}-web-dnsmasq
  labels:
    {{ include "icinga2.labels" . | indent 4 | trim }}
    component: web

data:
  entrypoint.sh: |-
    #/bin/sh

    echo "attempting to lookup {{ include "icinga2.fullname" . }}-master-1.{{ .Release.Namespace }}.svc.{{ default "cluster.local" .Values.clusterDomain }} @{{ .Values.nodeLocalDnsIp }} ..."
    MASTER_1_SVC_IP=$(dig +short "{{ include "icinga2.fullname" . }}-master-1.{{ .Release.Namespace }}.svc.{{ default "cluster.local" .Values.clusterDomain }}" @{{ .Values.nodeLocalDnsIp }} )
    echo "MASTER_1_SVC_IP=$MASTER_1_SVC_IP"

    {{ if not .Values.icinga2.master2.disable }}
    echo "attempting to lookup {{ include "icinga2.fullname" . }}-master-2.{{ .Release.Namespace }}.svc.{{ default "cluster.local" .Values.clusterDomain }} @{{ .Values.nodeLocalDnsIp }} ..."
    MASTER_2_SVC_IP=$(dig +short "{{ include "icinga2.fullname" . }}-master-2.{{ .Release.Namespace }}.svc.{{ default "cluster.local" .Values.clusterDomain }}" @{{ .Values.nodeLocalDnsIp }} )
    echo "MASTER_2_SVC_IP=$MASTER_2_SVC_IP"
    {{ end }}

    DNSMASQ_CMD=" \
      dnsmasq \
      --no-daemon \
      --domain-needed \
      --address=/{{ .Values.icinga2.master1.hostname }}/$MASTER_1_SVC_IP \
      {{ if not .Values.icinga2.master2.disable }}
      --address=/{{ .Values.icinga2.master2.hostname }}/$MASTER_2_SVC_IP \
      {{ end }}
      --server={{ .Values.nodeLocalDnsIp }} \
    "

    echo "running dnsmasq with: "
    echo $DNSMASQ_CMD
    eval $DNSMASQ_CMD
{{ end }}
