apiVersion: v1
kind: Service
metadata:
  name: {{ include "icinga2.fullname" . }}-web
  labels:
  {{- include "icinga2.labels" . | nindent 4}}
    component: web
spec:
  selector:
    {{ include "icinga2.selectorLabels" . | nindent 4 }}
    component: web
  ports:
    - name: http
      port: 80
      targetPort: 80
