{{- $fullName := include "icinga2.fullname" . }}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "icinga2.fullname" . }}-web
  labels:
    {{ include "icinga2.labels" . | indent 4 | trim }}
    component: web
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    {{ if .Values.icinga2.web.tlsSecret -}}
    - secretName: {{ .Values.icinga2.web.tlsSecret }}
    {{- else }}
    - secretName: {{ include "icinga2.fullname" . }}-web-tls
    {{- end }}
      hosts:
        - {{ .Values.icinga2.web.hostname }}
  rules:
    - host: "{{ .Values.icinga2.web.hostname }}"
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-web
                port:
                  number: 80
              {{- else }}
              serviceName: {{ $fullName }}-web
              servicePort: 80
              {{- end }}
