apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icinga2.fullname" . }}-web
  labels:
    {{ include "icinga2.labels" . | indent 4 | trim }}
    component: web

# data:

stringData:
  ICINGAWEB_DIRECTOR: "true"

  # various configuration parameters for web container (mostly kickstart)
  ICINGA2_WEB_PUBLIC_URL: {{ printf "%s/icinga" .Values.icinga2.web.hostname | quote }}

  KICKSTART_ADMIN_NAME:  {{ .Values.kickstart.adminName | quote }}
  KICKSTART_ADMIN_EMAIL: {{ .Values.kickstart.adminEmail | quote }}

  KICKSTART_PAGERDUTY_APIKEY: {{ .Values.kickstart.pagerdutyApiKey | default "" | quote }}

  KICKSTART_MATRIX_SERVER:  {{ .Values.kickstart.matrix.server | default "" | quote }}
  KICKSTART_MATRIX_ROOM_ID: {{ .Values.kickstart.matrix.roomId | default "" | quote }}
  KICKSTART_MATRIX_TOKEN:   {{ .Values.kickstart.matrix.token | default "" | quote }}

  # icinga2 master
  ICINGA2_MASTER:   {{ .Values.icinga2.master1.hostname | quote }}
  {{ if not .Values.icinga2.master2.disable }}
  ICINGA2_MASTER2:  {{ .Values.icinga2.master2.hostname | quote }}
  {{ end }}
  ICINGA2_PORT:     {{ .Values.icinga2.master.externalPort | quote }}
  ICINGA2_API_PORT: {{ .Values.icinga2.master.externalPort | quote }}
  ICINGA2_CMD_API_USER: {{ .Values.icinga2.auth.cmdApiUser | quote }}
  ICINGA2_CMD_API_PASS: {{ .Values.icinga2.auth.cmdApiPass | quote }}
  ICINGAWEB2_USERS:     "{{ .Values.icinga2.auth.webRootUser }}:{{ .Values.icinga2.auth.webRootPass }},{{ .Values.icinga2.auth.webDirectorUser }}:{{ .Values.icinga2.auth.webDirectorPass }}"
  ICINGAWEB2_DEPLOYERS: "{{ .Values.icinga2.auth.agentDeployUser }}:{{ .Values.icinga2.auth.agentDeployPass }}"

  {{ if .Values.icinga2.web.LDAP_AD -}}
  LDAP_AD: {{ .Values.icinga2.web.LDAP_AD     | quote }}
  LDAP_SERVER: {{ .Values.icinga2.web.LDAP_SERVER     | quote }}
  LDAP_PORT: {{ .Values.icinga2.web.LDAP_PORT     | quote }}
  LDAP_BIND_DN: {{ .Values.icinga2.web.LDAP_BIND_DN     | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.icinga2.web.LDAP_BIND_PASSWORD     | quote }}
  LDAP_BASE_DN: {{ .Values.icinga2.web.LDAP_BASE_DN     | quote }}
  LDAP_FILTER: {{ .Values.icinga2.web.LDAP_FILTER     | quote }}
  LDAP_ROLE_GROUPS: {{ .Values.icinga2.web.LDAP_ROLE_GROUPS     | quote }}
  LDAP_ROLE_PERMISSIONS: {{ .Values.icinga2.web.LDAP_ROLE_PERMISSIONS     | quote }}
  {{- end }}

  # director will access master 1 using the internal service LB and port
  # NOTE: Does now work correctly yet
  # ICINGA2_DIRECTOR_HOST:    {{ include "icinga2.fullname" . }}-master-1
  # ICINGA2_DIRECTOR_PORT:    "5665"

  # wait for master uptime
  ICINGA2_UPTIME:           {{ .Values.icinga2.web.waitForMasterUptime | quote }}

  # mysql
  MYSQL_HOST:                 {{ .Values.icinga2.mysql.host     | quote }}
  MYSQL_PORT:                 {{ .Values.icinga2.mysql.port     | quote }}
  MYSQL_ROOT_USER:            {{ .Values.icinga2.mysql.rootUser | quote }}
  MYSQL_ROOT_PASS:            {{ .Values.icinga2.mysql.rootPass | quote }}
  MYSQL_APP_USER_PERMISSIONS: {{ .Values.icinga2.mysql.ic2UserPermissions | quote }}

  WEB_DATABASE_USER:       "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  WEB_DATABASE_NAME:       "{{ .Values.icinga2.mysql.ic2DbPrefix }}web"
  WEB_DATABASE_PASS:        {{ .Values.icinga2.mysql.ic2UserPass | quote }}

  IDO_DATABASE_HOST:        {{ .Values.icinga2.mysql.host     | quote }}
  IDO_DATABASE_NAME:       "{{ .Values.icinga2.mysql.ic2DbPrefix }}ido"
  IDO_USER:                "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  IDO_PASSWORD:             {{ .Values.icinga2.mysql.ic2UserPass | quote }}

  # IcingaDB-Part
  {{ if .Values.icinga2.IcingaDB -}}
  ICINGADB_USER:           "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  ICINGADB_DATABASE_NAME:  "{{ .Values.icinga2.mysql.ic2UserPrefix }}icingadb"
  ICINGADB_PASSWORD:        {{ .Values.icinga2.mysql.ic2UserPass | quote }}
  ICINGADB_DATABASE_HOST:   {{ .Values.icinga2.mysql.host     | quote }}
  ICINGADB:                "true"
  {{- end }}

  MYSQL_DIRECTOR_USER:     "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  MYSQL_DIRECTOR_NAME:     "{{ .Values.icinga2.mysql.ic2DbPrefix }}director"
  MYSQL_DIRECTOR_PASS:      {{ .Values.icinga2.mysql.ic2UserPass | quote }}

  REPORTING_DATABASE_USER: "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  REPORTING_DATABASE_NAME: "{{ .Values.icinga2.mysql.ic2DbPrefix }}reporting"
  REPORTING_DATABASE_PASS:  {{ .Values.icinga2.mysql.ic2UserPass | quote }}

  VSPHEREDB_DATABASE_USER: "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  VSPHEREDB_DATABASE_NAME: "{{ .Values.icinga2.mysql.ic2DbPrefix }}vspheredb"
  VSPHEREDB_DATABASE_PASS:  {{ .Values.icinga2.mysql.ic2UserPass | quote }}

  X509_DATABASE_USER:      "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  X509_DATABASE_NAME:      "{{ .Values.icinga2.mysql.ic2DbPrefix }}x509"
  X509_DATABASE_PASS:       {{ .Values.icinga2.mysql.ic2UserPass | quote }}

  # grafana
  GRAFANA_HOST: {{ .Values.icinga2.grafana.host | quote }}
  GRAFANA_PORT: {{ .Values.icinga2.grafana.port | quote }}
  GRAFANA_ACCESS: {{ .Values.icinga2.grafana.mode | quote }}
  GRAFANA_PROTOCOL: {{ .Values.icinga2.grafana.protocol | quote }}
  GRAFANA_AUTHENTICATION: {{ .Values.icinga2.grafana.authentication | quote }}
  GRAFANA_AUTHENTICATION_TOKEN: {{ .Values.icinga2.grafana.token | quote }}
  GRAFANA_AUTHENTICATION_USERNAME: {{ .Values.icinga2.grafana.authenticationUsername | quote }}
  GRAFANA_AUTHENTICATION_PASSWORD: {{ .Values.icinga2.grafana.authenticationPassword | quote }}
  GRAFANA_ENABLE_LINK: "yes"
  GRAFANA_SHOW_DEBUG: "0"
  GRAFANA_PUBLIC: "yes"
  GRAFANA_PUBLIC_HOST: {{ .Values.icinga2.grafana.publicUrl | quote }}
  GRAFANA_PUBLIC_PROTOCOL: {{ .Values.icinga2.grafana.publicProtocol | quote }}
  GRAFANA_THEME: "light"
  GRAFANA_TIMERANGE: {{ .Values.icinga2.grafana.timerange | quote }}
  GRAFANA_TIMERANGE_ALL: {{ .Values.icinga2.grafana.timerange_all | quote }}
  GRAFANA_DASHBOARD_UID: {{ .Values.icinga2.grafana.dashboardUid | quote }}

  {{ if .Values.icinga2.graphite.enable }}
  # graphite
  GRAPHITE_HOST: {{ .Values.icinga2.graphite.host | quote }}
  GRAPHITE_HTTP_PORT: {{ .Values.icinga2.graphite.http_port | quote }}
  {{- end }}

  # icingaweb modules
  ICINGAWEB_AWS:          {{ .Values.icinga2.web.aws | quote }}
  ICINGAWEB_BP:           {{ .Values.icinga2.web.businessprocess | quote }}
  ICINGAWEB_CUBE:         {{ .Values.icinga2.web.cube | quote }}
  ICINGAWEB_DIRECTOR:     {{ .Values.icinga2.web.director | quote }}
  ICINGAWEB_FILESHIPPER:  {{ .Values.icinga2.web.fileshipper | quote }}
  ICINGAWEB_GLOBE:        {{ .Values.icinga2.web.globe | quote }}
  ICINGAWEB_IDOREPORTS:   {{ .Values.icinga2.web.idoreports | quote }}
  ICINGAWEB_MAP:          {{ .Values.icinga2.web.map | quote }}
  ICINGAWEB_PDF:          {{ .Values.icinga2.web.pdf | quote }}
  ICINGAWEB_REPORTING:    {{ .Values.icinga2.web.reporting | quote }}
  ICINGAWEB_TLV:          {{ .Values.icinga2.web.toplevelview | quote }}
  ICINGAWEB_VSPHEREDB:    {{ .Values.icinga2.web.vspheredb | quote }}
  ICINGAWEB_X509:         {{ .Values.icinga2.web.x509 | quote }}
