{{ if .Values.agent.enable -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "icinga2-agent.resname" . }}-agent
  labels: {{ include "icinga2-agent.labels" . | indent 4 }}
    component: agent

# data:

stringData:

  IC2_DIRECTOR_URI:     {{ .Values.director.uri | quote }}
  IC2_DIRECTOR_USER:    {{ .Values.director.user | quote }}
  IC2_DIRECTOR_PASS:    {{ .Values.director.pass | quote }}

  IC2_MASTER:           {{ .Values.master.ip | quote }}
  IC2_MASTER_2:         {{ .Values.master.ip2 | quote }}
  IC2_MASTER_PORT:      {{ .Values.master.port | quote }}

  IC2_AGENT_PUSH:                   {{ .Values.agent.push | quote }}
  IC2_ETH_INT:                      {{ .Values.agent.networkInterface | quote }}
  IC2_HOST_DISTRIBUTION:            {{ .Values.agent.hostDistribution | quote }}
  IC2_HOST_DISTRIBUTION_VERSION:    {{ .Values.agent.hostDistributionVersion | quote }}
  IC2_ROOT_DEVICE:                  {{ .Values.agent.rootDevice | quote }}
  IC2_INSTANCE_TYPE:                {{ .Values.agent.instanceType | quote }}
  {{ if .Values.agent.haproxy_host }}
  IC2_HAPROXY_HOST:                  {{ .Values.agent.haproxy_host | quote }}
  {{ end }}
  {{ if .Values.agent.haproxy_URL }}
  IC2_HAPROXY_URL:                  {{ .Values.agent.haproxy_URL | quote }}
  {{ end }}
  {{ if .Values.agent.detectIngress }}
  IC2_DETECT_INGRESS:               {{ .Values.agent.detectIngress | quote }}
  {{ end }}
  {{ if .Values.agent.EC2fetchTags }}
  IC2_FETCH_EC2_TAGS:               {{ .Values.agent.EC2fetchTags | quote }}
  {{ end }}

  # kubernetes
  {{ if .Values.kubernetes.host }}
  IC2_KUBE_HOST:               {{ .Values.kubernetes.host | quote }}
  IC2_KUBE_PORT:               {{ .Values.kubernetes.port | quote }}
  IC2_KUBE_SCHEME:             {{ .Values.kubernetes.scheme | quote }}
  {{ end }}
  {{ if .Values.kubernetes.token }}
  IC2_KUBE_PASS:               {{ .Values.kubernetes.token | quote }}
  {{ end }}

  # agent config variables
  {{ range $k, $v := .Values.agent.env }}
  {{ if eq (printf "%T" $v) "string" }}
  {{- $k }}: {{ $v | quote }}
  {{ else }}
  {{- $k }}: {{ $v | toJson | quote }}
  {{ end }}
  {{ end }}

  # master health check credentials
  IC2_MASTER_HEALTHCHECK_USER: {{ .Values.master.healthcheck.user | default "" | quote }}
  IC2_MASTER_HEALTHCHECK_PASSWORD: {{ .Values.master.healthcheck.password | default "" | quote }}

  IC2_DEBUG: {{ .Values.debug | default "0" | quote }}

{{ end }}
