{{ if .Values.companion.enable -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "icinga2-agent.resname" . }}-companion
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
metadata:
  name: {{ template "icinga2-agent.resname" . }}-companion
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
---
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "icinga2-agent.resname" . }}-companion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "icinga2-agent.resname" . }}-companion
subjects:
  - kind: ServiceAccount
    name: {{ template "icinga2-agent.resname" . }}-companion
    namespace: {{ .Release.Namespace }}
{{ end }}
