{{ if .Values.companion.enable -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "icinga2-agent.resname" . }}-companion
  labels: {{ include "icinga2-agent.labels" . | indent 4 }}
    component: companion

# data:

stringData:

  IC2_DIRECTOR_URI:     {{ .Values.director.uri | quote }}
  IC2_DIRECTOR_USER:    {{ .Values.director.user | quote }}
  IC2_DIRECTOR_PASS:    {{ .Values.director.pass | quote }}

  IC2_MASTER:           {{ .Values.master.ip | quote }}
  IC2_MASTER_2:         {{ .Values.master.ip2 | quote }}
  IC2_MASTER_PORT:      {{ .Values.master.port | quote }}

  IC2_AGENT_PUSH:                   {{ .Values.companion.push | quote }}
  IC2_INSTANCE_TYPE:                {{ .Values.companion.instanceType | quote }}

  # kubernetes
  {{ if .Values.kubernetes.host }}
  IC2_KUBE_HOST:               {{ .Values.kubernetes.host | quote }}
  IC2_KUBE_PORT:               {{ .Values.kubernetes.port | quote }}
  IC2_KUBE_SCHEME:             {{ .Values.kubernetes.scheme | quote }}
  {{ end }}
  {{ if .Values.kubernetes.token }}
  IC2_KUBE_PASS:               {{ .Values.kubernetes.token | quote }}
  {{ end }}

  # agent config variables
  {{ range $k, $v := .Values.companion.env }}
  {{ if eq (printf "%T" $v) "string" }}
  {{- $k }}: {{ $v | quote }}
  {{ else }}
  {{- $k }}: {{ $v | toJson | quote }}
  {{ end }}
  {{ end }}

  # master health check credentials
  IC2_MASTER_HEALTHCHECK_USER: {{ .Values.master.healthcheck.user | default "" | quote }}
  IC2_MASTER_HEALTHCHECK_PASSWORD: {{ .Values.master.healthcheck.password | default "" | quote }}

  IC2_DEBUG: {{ .Values.debug | default "0" | quote }}

{{ end }}
